name: SonarCloud Analysis

on:
  workflow_dispatch: 
   
jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Use a versão adequada do Node.js

    - name: Install dependencies
      run: npm install

    - name: Run SonarCloud analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
        SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
      run: npm run sonarqube
